package com.hibernateexample.util;

public interface Constraints {
	// Null checks ,blank checks and empty checks
	String ACCOUNT_NO_NULL = " ACCOUNT NUMBER REQUIRED BUT FOUND NULL";
	String ACCOUNT_NO_BLANK = " ACCOUNT NUMBER REQUIRED BUT FOUND BLANK";
	String ACCOUNT_NO_EMPTY = " ACCOUNT NUMBER REQUIRED BUT FOUND EMPTY";

	String FIRSTNAME_NULL = " ACCOUNT NUMBER REQUIRED BUT FOUND NULL";
	String FIRSTNAME_BLANK = " ACCOUNT NUMBER REQUIRED BUT FOUND BLANK";
	String FIRSTNAME_EMPTY = " ACCOUNT NUMBER REQUIRED BUT FOUND EMPTY";

	String LASTNAME_NULL = " ACCOUNT NUMBER REQUIRED BUT FOUND NULL";
	String LASTNAME_BLANK = " ACCOUNT NUMBER REQUIRED BUT FOUND BLANK";
	String LASTNAME_EMPTY = " ACCOUNT NUMBER REQUIRED BUT FOUND EMPTY";
	
	String MOBILE_NO_NULL="MOBILE NUMBER REQUIRED BUT FOUND NULL";
	String MOBILE_NO_BLANK="MOBILE NUMBER REQUIRED BUT FOUND BLANK";
	String MOBILE_NO_EMPTY="MOBILE NUMBER REQUIRED BUT FOUND EMPTY";

	// validation checks
	String ACCOUNT_NO_VALID = "PLEASE ENTER A VALIED ACCOUNT NUMBER";
	String MOBILE_NO_VALID = "PLEASE ENTER A VALID MOBILE NUMBER";
	String MOBILE_NO_SIZE="PLEASE A MOBILE NUMBER WITH 10 DIGITS";
	
	//expressions
	String MOBILE_PATTERN="(^$|[0-9]{10})";

}
